### ISSUE TITLE
Darwin native toolchain (x86_64) implies native-image target architecture class jdk.vm.ci.amd64.AMD64 but configured native-image target architecture is class jdk.vm.ci.aarch64.AArch64.

### ISSUE THREAD

**Issue by hutongsheng** [snicoll/demo-aot-native#7] opened 2024-02-07 09:29 UTC
hello , when i run ./mvnw -Pnative native:compile  , I encouter a prolbem . 

Darwin native toolchain (x86_64) implies native-image target architecture class jdk.vm.ci.amd64.AMD64 but configured native-image target architecture is class jdk.vm.ci.aarch64.AArch64.

I found a related question . the address is https://github.com/oracle/graal/issues/4694 .  but i dont know what java_home or java_version .  I try to send a email to him. but email was rejected.
the error maybe tell me , I use Darwin native toolchain (x86_64) to comiple  a jdk.vm.ci.aarch64.AArch64 target , instead of jdk.vm.ci.amd64.AMD64 .

my computer's system is apple m1 pro.  the java version i installed all is. aarch64 . 

whatever I change java_home to OpenJDK 64-Bit Server VM GraalVM 22.3.0 (build 17.0.5+8-LTS  
or  /Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.10+11.1/Contents/Home.  it still report this error . 

when i use native-image generate hellword binary .it does work . the link address is https://www.graalvm.org/latest/reference-manual/native-image/basics/ .

I have no idea . can you help me  ? 

thanks , appreciately

**Comment by snicoll** [comment] 2024-02-07 09:36
I am also on a Mac with ARM so it must be a problem on your end, and that question should have been raised on StackOverflow. That said, let's give it a try.

Please provide the output of `native-image --version`.

**Comment by hutongsheng** [comment] 2024-02-07 12:02
it show this : 
native-image --version
GraalVM 22.3.0 Java 17 CE (Java Version 17.0.5+8-LTS)
I also search stackoverflow about this issues ,

**Comment by sdeleuze** [comment] 2024-02-07 13:38
Can you please print the output of `cc --version ` and `echo $JAVA_HOME`?

**Comment by hutongsheng** [comment] 2024-02-08 04:44
> Can you please print the output of `cc --version ` and `echo $JAVA_HOME`?


cc --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

echo $JAVA_HOME
/Users/hutongsheng/.sdkman/candidates/java/current

java -version
openjdk version "17.0.5" 2022-10-18 LTS
OpenJDK Runtime Environment GraalVM 22.3.0 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM GraalVM 22.3.0 (build 17.0.5+8-LTS, mixed mode, sharing)

**Comment by hutongsheng** [comment] 2024-02-08 07:06
I found a strange problem . 
when I copy the maven printed command and paste it in macos terminal . it sucesss and generate a executable binary file .
and it can start up .
the command is Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.10+11.1/Contents/Home/bin/native-image -cp ...  package name . 
it print some message :

```
 Java version: 17.0.10+11-LTS, vendor version: Oracle GraalVM 17.0.10+11.1
 Graal compiler: optimization level: 2, target machine: armv8-a, PGO: off
 C compiler: cc (apple, arm64, 15.0.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 1 user-specific feature(s) .
```

but when I run ./mvnw -Pnative nativ:compile in idea terminal . it raise a error like this . 
it doesn't print java_version . graal compiler , cc etc . 

```
[ERROR] Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.27:compile (default-cli) on project demo-aot-native: Execution of /Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.10+11.1/Contents/Home/bin/native-image -cp /Users/hutongsheng/IdeaProjects/demo-aot-native/target/classes:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.1.4/spring-boot-starter-web-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter/3.1.4/spring-boot-starter-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot/3.1.4/spring-boot-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.1.4/spring-boot-autoconfigure-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.1.4/spring-boot-starter-logging-3.1.4.jar:/Users/hutongsheng/.m2/repository/ch/qos/logback/logback-classic/1.4.11/logback-classic-1.4.11.jar:/Users/hutongsheng/.m2/repository/ch/qos/logback/logback-core/1.4.11/logback-core-1.4.11.jar:/Users/hutongsheng/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.20.0/log4j-to-slf4j-2.20.0.jar:/Users/hutongsheng/.m2/repository/org/apache/logging/log4j/log4j-api/2.20.0/log4j-api-2.20.0.jar:/Users/hutongsheng/.m2/repository/org/slf4j/jul-to-slf4j/2.0.9/jul-to-slf4j-2.0.9.jar:/Users/hutongsheng/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/Users/hutongsheng/.m2/repository/org/yaml/snakeyaml/1.33/snakeyaml-1.33.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.1.4/spring-boot-starter-json-3.1.4.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.15.2/jackson-databind-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.15.2/jackson-annotations-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.15.2/jackson-core-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.15.2/jackson-datatype-jdk8-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.15.2/jackson-datatype-jsr310-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.15.2/jackson-module-parameter-names-2.15.2.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.1.4/spring-boot-starter-tomcat-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.13/tomcat-embed-core-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.13/tomcat-embed-el-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.13/tomcat-embed-websocket-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-web/6.0.12/spring-web-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-beans/6.0.12/spring-beans-6.0.12.jar:/Users/hutongsheng/.m2/repository/io/micrometer/micrometer-observation/1.11.4/micrometer-observation-1.11.4.jar:/Users/hutongsheng/.m2/repository/io/micrometer/micrometer-commons/1.11.4/micrometer-commons-1.11.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-webmvc/6.0.12/spring-webmvc-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-aop/6.0.12/spring-aop-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-context/6.0.12/spring-context-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-expression/6.0.12/spring-expression-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-core/6.0.12/spring-core-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-jcl/6.0.12/spring-jcl-6.0.12.jar --no-fallback -o /Users/hutongsheng/IdeaProjects/demo-aot-native/target/demo-aot-native -H:ConfigurationFileDirectories=/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/org.apache.tomcat.embed/tomcat-embed-core/10.0.20,/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/ch.qos.logback/logback-classic/1.4.1,/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/com.fasterxml.jackson.core/jackson-databind/2.15.2 returned non-zero result -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.graalvm.buildtools:native-maven-plugin:0.9.27:compile (default-cli) on project demo-aot-native: Execution of /Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.10+11.1/Contents/Home/bin/native-image -cp /Users/hutongsheng/IdeaProjects/demo-aot-native/target/classes:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.1.4/spring-boot-starter-web-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter/3.1.4/spring-boot-starter-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot/3.1.4/spring-boot-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.1.4/spring-boot-autoconfigure-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.1.4/spring-boot-starter-logging-3.1.4.jar:/Users/hutongsheng/.m2/repository/ch/qos/logback/logback-classic/1.4.11/logback-classic-1.4.11.jar:/Users/hutongsheng/.m2/repository/ch/qos/logback/logback-core/1.4.11/logback-core-1.4.11.jar:/Users/hutongsheng/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.20.0/log4j-to-slf4j-2.20.0.jar:/Users/hutongsheng/.m2/repository/org/apache/logging/log4j/log4j-api/2.20.0/log4j-api-2.20.0.jar:/Users/hutongsheng/.m2/repository/org/slf4j/jul-to-slf4j/2.0.9/jul-to-slf4j-2.0.9.jar:/Users/hutongsheng/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/Users/hutongsheng/.m2/repository/org/yaml/snakeyaml/1.33/snakeyaml-1.33.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.1.4/spring-boot-starter-json-3.1.4.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.15.2/jackson-databind-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.15.2/jackson-annotations-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.15.2/jackson-core-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.15.2/jackson-datatype-jdk8-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.15.2/jackson-datatype-jsr310-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.15.2/jackson-module-parameter-names-2.15.2.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.1.4/spring-boot-starter-tomcat-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.13/tomcat-embed-core-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.13/tomcat-embed-el-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.13/tomcat-embed-websocket-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-web/6.0.12/spring-web-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-beans/6.0.12/spring-beans-6.0.12.jar:/Users/hutongsheng/.m2/repository/io/micrometer/micrometer-observation/1.11.4/micrometer-observation-1.11.4.jar:/Users/hutongsheng/.m2/repository/io/micrometer/micrometer-commons/1.11.4/micrometer-commons-1.11.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-webmvc/6.0.12/spring-webmvc-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-aop/6.0.12/spring-aop-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-context/6.0.12/spring-context-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-expression/6.0.12/spring-expression-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-core/6.0.12/spring-core-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-jcl/6.0.12/spring-jcl-6.0.12.jar --no-fallback -o /Users/hutongsheng/IdeaProjects/demo-aot-native/target/demo-aot-native -H:ConfigurationFileDirectories=/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/org.apache.tomcat.embed/tomcat-embed-core/10.0.20,/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/ch.qos.logback/logback-classic/1.4.1,/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/com.fasterxml.jackson.core/jackson-databind/2.15.2 returned non-zero result
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:53)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:152)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:76)
Caused by: org.apache.maven.plugin.MojoExecutionException: Execution of /Library/Java/JavaVirtualMachines/graalvm-jdk-17.0.10+11.1/Contents/Home/bin/native-image -cp /Users/hutongsheng/IdeaProjects/demo-aot-native/target/classes:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-web/3.1.4/spring-boot-starter-web-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter/3.1.4/spring-boot-starter-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot/3.1.4/spring-boot-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.1.4/spring-boot-autoconfigure-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.1.4/spring-boot-starter-logging-3.1.4.jar:/Users/hutongsheng/.m2/repository/ch/qos/logback/logback-classic/1.4.11/logback-classic-1.4.11.jar:/Users/hutongsheng/.m2/repository/ch/qos/logback/logback-core/1.4.11/logback-core-1.4.11.jar:/Users/hutongsheng/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.20.0/log4j-to-slf4j-2.20.0.jar:/Users/hutongsheng/.m2/repository/org/apache/logging/log4j/log4j-api/2.20.0/log4j-api-2.20.0.jar:/Users/hutongsheng/.m2/repository/org/slf4j/jul-to-slf4j/2.0.9/jul-to-slf4j-2.0.9.jar:/Users/hutongsheng/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/Users/hutongsheng/.m2/repository/org/yaml/snakeyaml/1.33/snakeyaml-1.33.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-json/3.1.4/spring-boot-starter-json-3.1.4.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.15.2/jackson-databind-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.15.2/jackson-annotations-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.15.2/jackson-core-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.15.2/jackson-datatype-jdk8-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.15.2/jackson-datatype-jsr310-2.15.2.jar:/Users/hutongsheng/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.15.2/jackson-module-parameter-names-2.15.2.jar:/Users/hutongsheng/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/3.1.4/spring-boot-starter-tomcat-3.1.4.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/10.1.13/tomcat-embed-core-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/10.1.13/tomcat-embed-el-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/10.1.13/tomcat-embed-websocket-10.1.13.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-web/6.0.12/spring-web-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-beans/6.0.12/spring-beans-6.0.12.jar:/Users/hutongsheng/.m2/repository/io/micrometer/micrometer-observation/1.11.4/micrometer-observation-1.11.4.jar:/Users/hutongsheng/.m2/repository/io/micrometer/micrometer-commons/1.11.4/micrometer-commons-1.11.4.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-webmvc/6.0.12/spring-webmvc-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-aop/6.0.12/spring-aop-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-context/6.0.12/spring-context-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-expression/6.0.12/spring-expression-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-core/6.0.12/spring-core-6.0.12.jar:/Users/hutongsheng/.m2/repository/org/springframework/spring-jcl/6.0.12/spring-jcl-6.0.12.jar --no-fallback -o /Users/hutongsheng/IdeaProjects/demo-aot-native/target/demo-aot-native -H:ConfigurationFileDirectories=/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/org.apache.tomcat.embed/tomcat-embed-core/10.0.20,/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/ch.qos.logback/logback-classic/1.4.1,/Users/hutongsheng/IdeaProjects/demo-aot-native/target/graalvm-reachability-metadata/35d3b6502e9bcd13443b74777bb44900c3d3b151/com.fasterxml.jackson.core/jackson-databind/2.15.2 returned non-zero result
    at org.graalvm.buildtools.maven.AbstractNativeImageMojo.buildImage (AbstractNativeImageMojo.java:418)
    at org.graalvm.buildtools.maven.NativeCompileNoForkMojo.execute (NativeCompileNoForkMojo.java:96)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.apache.maven.wrapper.BootstrapMainStarter.start (BootstrapMainStarter.java:53)
    at org.apache.maven.wrapper.WrapperExecutor.execute (WrapperExecutor.java:152)
    at org.apache.maven.wrapper.MavenWrapperMain.main (MavenWrapperMain.java:76)
```

**Comment by sdeleuze** [comment] 2024-02-08 07:35
The `cc -version` tells you are using a arm64 toolchain which is what is expected. Make sure you don't have any Darwin native toolchain for x86_64 installed (not sure if that's possible, maybe with Rosetta).

I am not sure what happens, sometime this kind of behavior can be caused by an inconsistency between `JAVA_HOME` environment variable and the `PATH` one. I would advise to remove entries manually added to `PATH` and use https://sdkman.io/ to switch between SDKs.

**Comment by snicoll** [comment] 2024-02-08 08:52
@hutongsheng I am going to close this now as we've determined the issue to be on your end. Hopefully, the information that was provided will help you sort it out. If that's not the case, I would recommend searching on StackOverflow for a similar question and raise one if you're still experiencing an issue.

**Closed as not planned by snicoll** 2024-02-08 08:52 UTC
